<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess_page() to add header image class.
 */
function oc_bootstrap_preprocess_page(&$variables) {
  $variables['banner_image_class'] = '';
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if ($node->redfin_header_image->value) {
      $variables['banner_image_class'] = 'image-'.$node->redfin_header_image->value;
    }
  }
}
